//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncabezadoPedidos
    {
        public string NumeroPedido { get; set; }
        public string UsuarioPedido { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal CostoTotalPedido { get; set; }
        public bool PedidoProcesado { get; set; }
        public bool PedidoEnviado { get; set; }
    }
}
